// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3UTOYP7v6lRmJQeNN45GcqDyatrB5QcQ',
    appId: '1:1009312908196:web:44e9e7b8cdd2c7089bf731',
    messagingSenderId: '1009312908196',
    projectId: 'dexter-todo-app',
    authDomain: 'dexter-todo-app.firebaseapp.com',
    storageBucket: 'dexter-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEYmknYR-OQL3XKohZ3xjLBI0WgaHcsY',
    appId: '1:1009312908196:android:7fde6763e5d795999bf731',
    messagingSenderId: '1009312908196',
    projectId: 'dexter-todo-app',
    storageBucket: 'dexter-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYCTTYnp8HIL6cVkeKUI--0gZdI_8vwE',
    appId: '1:1009312908196:ios:8f0d1b30a8f272ad9bf731',
    messagingSenderId: '1009312908196',
    projectId: 'dexter-todo-app',
    storageBucket: 'dexter-todo-app.appspot.com',
    iosClientId: '1009312908196-vrimn0bavua9motkmou217ioe5cbv38v.apps.googleusercontent.com',
    iosBundleId: 'com.dexter.todo.dexterTodo',
  );
}
